version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "shipping-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jdsjn5j47s0u"
s3_prefix = "shipping-api"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
